version: "2"
services:
  food_service:
    container_name: food_service
    build: ./
    restart: always
    ports:
      - "3001:3000"
    command: npm run dev
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - budget_app_network
networks:
  budget_app_network:
    external: true
